### ISSUE TITLE
Funciona en laravel 11?

### ISSUE THREAD

**Issue by agaitan026** [shino47/laravel-yappy-checkout#1]
Buenas noches bro, será que sirve en laravel 11? O yappy habrá hechos cambios?

saludos

**Comment by shino47** [comment]
Qué tal. Acabé de revisar y el SDK de PHP es el mismo que hace 3 años, la v1.280. 
Del lado de Yappy no creo que hayan cambios. 
Para Laravel 11 quizás sí funcione. La única dependencia del proyecto es Guzzle y es la misma versión que utiliza Laravel 11.
Ahora mismo no tengo ningún proyecto que tenga el botón de pago Yappy, así que no puedo hacer pruebas.

Saludos.

**Comment by agaitan026** [comment]
gracias
